// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraphQLPoC.Entities;

public partial class Book
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? AuthorId { get; set; }
}